name: flamethrower-dns
base: core24
version: '0.1'
website: https://github.com/cpg1111/flamethrower-snap
source-code: https://github.com/cpg1111/flamethrower-snap
summary: Flamethrower DNS performance test tool
description: |
  Flamethrower is a small, fast, configurable tool for functional testing,
  benchmarking, and stress testing DNS servers and networks. It supports IPv4,
  IPv6, UDP, TCP, DoT, and DoH and has a modular system for
  generating queries used in the tests.
license: Apache-2.0

grade: stable
confinement: strict

apps:
  flamethrower-dns:
    command: usr/local/bin/flame
    plugs:
      - network
      - network-bind
      - network-observe

parts:
  flamethrower:
    plugin: cmake
    cmake-parameters:
      - -DDOH_ENABLE=ON
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    build-packages:
      - g++
      - pkgconf
      - libuv1-dev
      - libldns-dev
      - libgnutls28-dev
      - libnghttp2-dev
    stage-packages:
      - libuv1
      - libldns3
      - nghttp2
    source-type: git
    source: https://github.com/dns-oarc/flamethrower
    source-branch: master
